import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 11,
  },
  headerContainer: {
    marginTop: 20,
    justifyContent: 'space-between',
    color: '#000000',
    fontFamily: 'montserrat',
  },
  cityTitle: {
    fontSize: 32,
    fontWeight: 'bold',
  },
  locationText: {
    fontSize: 14,
  },
  temperature: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#000000',
    justifyContent: 'flex-end',
    flexDirection: 'row',
    paddingHorizontal: 20,
    paddingEnd: 10,
    fontFamily: 'monospace',
  },
  searchContainer: {
    marginTop: 13,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#A8CCF0',
    borderRadius: 30,
    paddingHorizontal: 20,
    paddingVertical: 15,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 1,
    elevation: 3,
    opacity: 0.4,
  },
  searchIcon: {
    marginRight: 10,
  },
  searchInput: {
    flex: 1,
    fontSize: 16,
  },
  searchLoader: {
    marginLeft: 10,
  },
  tabsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: 33,
    backgroundColor: '#FFF',
    borderRadius: 15,
  },
  activeTab: {
    paddingVertical: 8,
    paddingHorizontal: 15,
    borderRadius: 30,
    backgroundColor: '#A8CCF0',
    opacity: 0.7,
  },
  activeTabText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#176FF2',
    fontFamily: 'Abhaya Libre Medium',
  },
  inactiveTab: {
    paddingVertical: 8,
    paddingHorizontal: 15,
    borderRadius: 20,
    backgroundColor: '#FFF',
  },
  inactiveTabText: {
    fontSize: 16,
    color: '#B8B8B8',
    fontFamily: 'Abhaya Libre Medium',
  },
  sectionTitle: {
    fontSize: 21,
    fontWeight: '600',
    marginTop: 45,
    paddingHorizontal: 10,
  },
  placesScrollView: {
    flexDirection: 'row',
    paddingVertical: 10,
  },
  placeCard: {
    width: 150,
    height: 200,
    backgroundColor: '#FFF',
    borderRadius: 15,
    marginRight: 15,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
  },
  placeImage: {
    width: '100%',
    height: '100%',
    borderRadius: 15,
  },
  placeOverlay: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: 'rgba(0,0,0,0.5)',
    paddingVertical: 5,
    alignItems: 'center',
  },
  placeName: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#FFF',
  },
  navigationButton: {
    backgroundColor: '#007bff',
    paddingVertical: 8,
    borderRadius: 10,
    alignItems: 'center',
    marginVertical: 5,
    marginHorizontal: 10,
  },
  navigationButtonText: {
    color: '#FFF',
    fontWeight: 'bold',
  },
  searchBar: {
    flex: 1,
    width: '100%',
    paddingHorizontal: 10,
    fontSize: 16,
    color: '#333',
    fontFamily: 'Abhaya Libre Medium',
  },
  cityName: {
    fontSize: 32,
    fontWeight: '600',
  },
  headerTitle: {
    fontSize: 18,
  },
  bottomNav: {
    position: 'absolute',
    bottom: 10,
    left: 20,
    right: 20,
    flexDirection: 'row',
    backgroundColor: '#FFF',
    borderRadius: 25,
    padding: 10,
    justifyContent: 'space-around',
    elevation: 5,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 5,
  },
  navIcon: {
    padding: 10,
  },
});

export default styles;
